### PR TITLE
Tomlm/azbotpublish

### LINKED ISSUE #834: MSBot: EchoBot created using VSIX fails to deploy
## Tool
Name: Msbot
Version: 4.2.0-103 installed from [botbuilder.myget.org](https://botbuilder.myget.org/feed/botbuilder-tools-daily/package/npm/msbot).
OS: *Windows 10*

## To Reproduce
1. Create a bot using C# VSIX [download link](https://botbuilder.myget.org/F/aitemplates/vsix/BotBuilderV4.fbe0fc50-a6f1-4500-82a2-189314b7bea2-4.1.7.59.vsix ).
2. Run the following command:
`msbot clone services -f deploymentScripts\msbotClone -l westus2 --verbose --proj-file MyBot.csproj -n MyBotClone001`
3. You get the following error:

`Command failed: dotnet user-secrets set botFileSecret +K6wQP9aYJ9ieS8=Could not find the global property 'UserSecretsId' in MSBuild project`

`'C:\Temp\WorkingBots\MyBot\MyBot\MyBot.csproj'. Ensure this property is set in the project or use the '--id' command line option.`

## Expected behavior
A bot should be provisioned in the Azure portal.

[bug]

### PR DESCRIPTION
**Pull request by tomlm**
Fixes #834 

## Proposed Changes
make suer there is a secret id
drop publish.cmd /publish.sh scripts

### CODE REVIEW

File: packages/MSBot/src/msbot-clone-services.ts [hunk 1]
```diff
@@ -829,6 +830,20 @@ async function updateLocalSafeSettings(azBot?: IBotService): Promise<void> {
             fs.writeFileSync('appsettings.json', JSON.stringify(settings, null, 4), { encoding: 'utf8' });
 
             if (args.secret) {
+
+                // some projfiles won't have a userSecret set, check for it
```
Comment (carlosscastro) [inline packages/MSBot/src/msbot-clone-services.ts]: profiles
