### PR TITLE
minor typo fix

### LINKED ISSUE #1080: Region typos in LUIS CLI
## Tool
Name: LUIS
Version: 2.4.0
OS: Windows

## Describe the bug
There are typos in the valid LUIS regions:
`eastus is not a valid authoring region.  Valid values are [westus|westeuerope|australiaest]`

## To Reproduce
Try deploying LUIS app on an invalid region and get the error response.

## Expected behavior
Regions should be `westeurope`, `australiaeast`?

## Additional context

[bug]

### PR DESCRIPTION
**Pull request by mdrichardson**
Fixes #1080 

## Proposed Changes

* `westeuerope` => `westeurope`
* `australiaest` => `australiaeast`
* Added `virginia` to output of acceptable args
  * The code already considers it acceptable, I just added it to the output that notifies the user of acceptable commands

This was the only location with the typo and it was in a string, so will not affect the rest of the code base.

### CODE REVIEW

File: packages/LUIS/bin/luis.js [hunk 1]
```diff
@@ -950,7 +950,7 @@ function validateConfig(config) {
 
     assert(typeof authoringKey === 'string', `The authoringKey  ${messageTail}`);
     assert(typeof region === 'string', `The region ${messageTail}`);
-    assert(args.region == "westus" || args.region == 'westeurope' || args.region == 'australiaeast' || args.region == 'virginia', `${args.region} is not a valid authoring region.  Valid values are [westus|westeuerope|australiaest]`);
+    assert(args.region == "westus" || args.region == 'westeurope' || args.region == 'australiaeast' || args.region == 'virginia', `${args.region} is not a valid authoring region.  Valid values are [westus|westeurope|australiaeast|virginia]`);
```
Comment (stevengum) [inline packages/LUIS/bin/luis.js]: @mdrichardson, does there need to be additional logic for supporting `'virginia'`? It looks like the authoring endpoint for this region is: https://virginia.api.cognitive.microsoft.us/luis/v2.0

More [info](https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-services-aiandcognitiveservices#language-understanding-luis).

Also, can you change `"westus"` to be `'westus'`? Thanks 😄

Comment (mdrichardson) [reply packages/LUIS/bin/luis.js]: Fixed the double quotes. As far as I know, there doesn't need to be additional logic. It was already accepted before; it just didn't show up in the "acceptable regions" message. But maybe that was intentional since it's gov?
